version: '3'
services:
  sandbox-quickjs:
    build:
      context: ./sandbox-quickjs/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - HOST=sandbox-quickjs
      - PORT=8081
    # networks:
    # - intranet
# networks:
#   intranet:
#     internal: true